#!/usr/bin/env bun
/**
 * Copies the version from config.yaml into src/version.ts.
 *
 * config.yaml is what Supervisor reads, so it is the source of truth; this
 * makes the running server able to state the same number without a human
 * remembering to update it in two places.
 */
const yaml = await Bun.file(new URL("../config.yaml", import.meta.url)).text();
const match = yaml.match(/^version:\s*"([^"]+)"/m);
if (!match) {
  console.error("no version: line in config.yaml");
  process.exit(1);
}
const version = match[1];
const target = new URL("../src/version.ts", import.meta.url);
const body = `/**
 * The add-on's version, baked in at build time from config.yaml.
 *
 * config.yaml is the single source of truth because Supervisor reads it to
 * decide what is installed and what an update means. Duplicating the number in
 * package.json or a constant here would create a second truth that drifts, and
 * the drift only shows up when someone is trying to work out which build is
 * actually running.
 *
 * Generated by scripts/sync-version.ts — do not edit by hand.
 */
export const VERSION = "${version}";
`;
await Bun.write(target, body);
console.log(`version.ts → ${version}`);
