/**
 * The add-on's version, baked in at build time from config.yaml.
 *
 * config.yaml is the single source of truth because Supervisor reads it to
 * decide what is installed and what an update means. Duplicating the number in
 * package.json or a constant here would create a second truth that drifts, and
 * the drift only shows up when someone is trying to work out which build is
 * actually running.
 *
 * Generated by scripts/sync-version.ts — do not edit by hand.
 */
export const VERSION = "0.28.0";
